### ISSUE TITLE
Describe meaning of placeholder "site.post" in index.md

### ISSUE THREAD

**Issue by samundra** [developers-nepal/php#35]
## Wiki Update

index.md contains "site.post" placeholder which at current moment is not in use. 

@hardfire it would be nicer if we could add information on these things. if this has already been somewhere we can just link to that post and close this issue.

**Comment by hardfire** [comment]
Hey yes! site.post is the default blog post that comes with jekyll. I left it there in case we will use it sometime in the future. We could remove it as well because its not used. Or it stays and someday if we'll use it we can start writing posts . I don't mind either

**Comment by samundra** [comment]
if we are thinking to use **site.post** someday in future let's keep it intact and it will service as place holder. Closing this thread now. Hope this serves as future reference.
