### ISSUE TITLE
use huboard

### ISSUE THREAD

**Issue by geshan** [developers-nepal/php#5]
https://huboard.com/developers-nepal/php/board/create

**Comment by hardfire** [comment]
I would not add huboard to the whole organization but only to the php respository. just because rest are territories we don't own, atleast in my mind :D . Added it as a service. does it work ? @geshan

**Comment by hardfire** [comment]
guess, it doesnt work that way, granting access to the whole organization.

**Comment by hardfire** [comment]
now, you know more about configuring huboard, please continue from there on :D @geshan
